version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
     ignore:
      - dependency-name: "mypy"
        versions: [">=2"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
